### Test POST /signup
POST http://localhost:8080/signup
Content-Type: application/json

{
  "name": "Doe",
  "age": 40,
  "email": "john.doe@example.com",
  "password": "123"
}

### Test POST /login
POST http://localhost:8080/login
Content-Type: application/json

{
  "name": "Doe",
  "age": 40,
  "email": "john.doe@example.com",
  "password": "123"
}

### Test POST /api/login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "name": "Doe",
  "age": 40,
  "email": "john.doe@example.com",
  "password": "123"
}


### Test GET /user/id
GET http://localhost:8080/user/id?id=1
Accept: application/json


### Test GET /users
GET http://localhost:8080/users
Accept: application/json

### Test PUT /user/id
PUT http://localhost:8080/user/id?id=1
Content-Type: application/json

{
  "name": "John Doe",
  "age": 20,
  "email": "john.doe@gmail.com",
  "password": "12345"
}

### Test DELETE /user/id
DELETE http://localhost:8080/user/id?id=1
Accept: application/json